[#1369] SynchronizerState refactor
Electric-Coin-Company/zcash-swift-wallet-sdk pull request #1372
Opened 2024-02-06 11:29 UTC by LukasKorba

Closes #1369 

- Transaprent balance removed from SynchronizerState, all balances are now handled with AccountBalance
- WalletBalance has been removed from the SDK, replaced with AccountBalance
- public APIs for individual balances (getTransparent, getShielded, getShieldedVerfied) have been removed from the SDK, replaced with getAccountBalance
- tests refactored

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-02-06 14:48 UTC, str4d requested changes
Reviewed 12843fb261e11d5a62219016d219adcc139b5908.

2024-02-06 16:16 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        try await initializer.rustBackend.getWalletSummary()?.accountBalances[UInt32(accountIndex)] ?? .zero
Changed back to optional AccountBalance?

2024-02-06 16:39 UTC, LukasKorba commented on Tests/DarksideTests/RewindRescanTests.swift
> +        let initialTotalBalance: Zatoshi = try await coordinator.synchronizer.getAccountBalance().saplingBalance.total()
done everywhere where it was applicable

2024-02-12 07:52 UTC, HonzaR approved these changes

2024-02-12 15:20 UTC, str4d approved these changes
utACK 3d0acdef3cdd81b66d0044f4bf31ba2c2d154533 with question.

2024-02-12 15:20 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        let tBalance: Zatoshi = try await self.getAccountBalance(accountIndex: accountIndex)?.unshielded ?? .zero
Non-blocking nit: if `spendingKey.account` is incorrect (not a known account) then this will report `ZcashError.synchronizerShieldFundsInsuficientTransparentFunds`, which is _technically_ true, but a more useful error would be that the spending key does not belong to the wallet.

2024-02-12 15:20 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            accountBalance: try? await getAccountBalance(),
I don't understand what the `try?` on this line does, because the `SynchronizerState` constructor doesn't take `accountBalance` as a nullable value here, and the `snapshotState` method does not have a `throws` declaration.

2024-02-12 16:04 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            accountBalance: try? await getAccountBalance(),
```swift
public struct SynchronizerState: Equatable {
    public var syncSessionID: UUID
    public var accountBalance: AccountBalance?
    //...
```
The `SynchronizerState` hold an Optional AccountBalance so it can be nil and that is exactly what try? does. If for any reason getAccountBalance() fails, nil is passed and clients can respond accordingly.

2024-02-12 16:40 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            accountBalance: try? await getAccountBalance(),
Ah okay, I missed that this also changed in the PR. I viewed this file and then searched for `SynchronizerState` from that page; apparently that navigated me to the version of `SynchronizerState` in `main`, not this branch.

2024-02-12 16:41 UTC, merged