Expose APIs for working with transaction proposals
Electric-Coin-Company/zcash-swift-wallet-sdk pull request #1382
Opened 2024-02-21 01:02 UTC by str4d

Closes Electric-Coin-Company/zcash-swift-wallet-sdk#1204.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-02-21 01:23 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            try await transactionEncoder.submit(transaction: encodedTransaction)
Currently the entire method throws an error if the submission fails (either due to a gRPC error, or due to getting an error in the response from `lightwalletd`). This code should instead collect the first error that occurs, not attempt to submit any subsequent transactions, and return to the caller the three separate categories of transactions (submitted, failed, not attempted). [I do this with a `Flow` in the Android SDK](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/pull/1397/files#diff-4b4a0b33c9b47a30dbd2e951c80e04c51b5be81ca83b2a36546c0c4400785b77R579-R595), but I don't know the equivalent right way to do this in Swift. cc @LukasKorba.

2024-02-22 01:55 UTC, nuttycom approved these changes
utACK with questions that we should probably create follow-up issues to address.

2024-02-22 01:55 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func proposeShielding(
I'm concerned that as a high-level API, this will not adequately protect the user's privacy because it will potentially link addresses. At the SDK level, do we provide the ability to generate diversified addresses? If so, there might be a preexisting problem here with the existing methods that are exposed.

2024-02-22 01:55 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            if (submitFailed) {
```suggestion
            if submitFailed {
```

2024-02-22 01:55 UTC, nuttycom commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    func proposeTransfer(
Now that we have this functionality and also https://github.com/Electric-Coin-Company/zcash-light-client-ffi/pull/115, we should be able to expose the latter in the API?

2024-02-22 01:55 UTC, nuttycom commented on Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
> +        return [try await repository.find(rawID: txId)]
Does `repository.find` throw if it cannot find the txid? I would think that ideally that would return an optional result, so that "not found" is distinguished from "error" (though in this particular case you'd want to throw an error anyway, so it's nonblocking for now.)

2024-02-22 01:55 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
While you're touching this file, please fix the unterminated `swiftlint:disable`.

2024-02-22 14:53 UTC, str4d commented on Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
> +        return [try await repository.find(rawID: txId)]
We shouldn't encounter this case (successful wallet DB lookup that returns no result) because if we reach here, the transaction was successfully created by the Rust backend (and didn't itself result in an exception). Any exception thrown here would instead be due to database access failures, which are indeed exceptions.

2024-02-26 18:29 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// If `prepare()` hasn't already been called since creating of synchronizer instance or since the last wipe then this method throws
```suggestion
    /// If `prepare()` hasn't already been called since creation of the synchronizer instance or since the last wipe then this method throws
```

2024-02-26 18:31 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter memo: an optional  memo to include as part of the proposal's transactions. Use `nil` when sending to transparent receivers otherwise the function will throw an error.
```suggestion
    /// - Parameter memo: an optional memo to include as part of the proposal's transactions. Use `nil` when sending to transparent receivers otherwise the function will throw an error.
```

2024-02-26 18:35 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter memo: an optional memo to include as part of the proposal's transactions.
`shieldingThreshold` needs to be documented both here and on the deprecated version.

2024-02-26 18:39 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func proposeShielding(
This is not a regression so I'm fine with it for now. The Right Thing here is to do something similar to what we did for the Sprout->Sapling transition, or make the timing of shielding transactions follow a Poisson distribution.

2024-02-26 18:39 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// Creates the transactions in the given proposal
```suggestion
    /// Creates the transactions in the given proposal.
```

2024-02-26 18:40 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter proposal: the proposal to create.
```suggestion
    /// - Parameter proposal: the proposal for which to create transactions.
```

2024-02-26 18:42 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter spendingKey: the `UnifiedSpendingKey` associated with the notes that will be spent.
```suggestion
    /// - Parameter spendingKey: the `UnifiedSpendingKey` associated with the account for which the proposal was created.
```

2024-02-26 18:43 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
>      ///
Document `shieldingThreshold`.

2024-02-26 19:03 UTC, daira commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    /// - Parameter memo: an optional  memo to include as part of the proposal's transactions. Use `nil` when sending to transparent receivers otherwise the function will throw an error.
Revert back to `memoBytes`.

2024-02-26 19:05 UTC, daira commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    /// - Parameter memo: an optional memo to include as part of the proposal's transactions.
Document `shieldingThreshold`.

2024-02-26 19:06 UTC, daira commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    /// If `prepare()` hasn't already been called since creating of synchronizer instance or since the last wipe then this method throws
```suggestion
    /// If `prepare()` hasn't already been called since creation of the synchronizer instance or since the last wipe then this method throws
```

2024-02-26 19:07 UTC, daira commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    /// Creates the transactions in the given proposal
```suggestion
    /// Creates the transactions in the given proposal.
```

2024-02-26 19:07 UTC, daira commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    /// - Parameter proposal: the proposal to create.
Same change as above.

2024-02-27 15:44 UTC, str4d commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    func proposeTransfer(
Yes; @pacu is working on that in #1380.

2024-02-27 16:04 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
I don't see any.

2024-02-27 16:05 UTC, str4d commented
[Force-pushed](https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/compare/4d4d7492cb7916ded6ab2a1b7a0894847a470690..cf6d4a115b85d801f886714d7927833db3919c40) to address review comments.

2024-02-27 16:59 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
Oh, you mean the "Blanket Disable Command Violation"? IDK what the intention is there, that's a question for @LukasKorba (and should probably be addressed in a separate PR).

2024-02-27 19:31 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func proposeShielding(
I'm not talking about timing here, although that is also a concern; with this API as written, it provides no mechanism for wallets that have given out UAs to different parties to select which transparent receivers the funds should be spent from in shielding. So any concurrent transparent receives to distinct Unified Addresses will be linked. The Rust API takes a vector of transparent addresses to shield from, so that wallets can choose to link addresses if they want but aren't compelled to: https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/data_api/wallet.rs#L1195

2024-02-27 23:42 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func proposeShielding(
In a pairing today, @nuttycom and I decided that we will change `Synchronizer.proposeShielding` in two ways:
- It will take an optional transparent receiver, corresponding to a specific diversified UA (or the default transparent address) that should have its transparent funds shielded.
  - If the transparent receiver is not part of the specified account, an error will be returned.
  - If no receiver is provided, the current behaviour of "shield transparent funds in whichever transparent receiver under the account has them" will be used.
- It will return an error if there are transparent funds in more than one transparent receiver in the given account.
  - This fixes an address linkability problem that currently exists with `Synchronizer.shieldFunds`, wherein a transaction spending funds from multiple transparent receivers in the same account can be created which indelibly links them on-chain.
  - We are not fixing the problem in `Synchronizer.shieldFunds` because working around it would require changing the `shieldFunds` API, but we are deprecating and soon removing the method instead.

The transparent receiver argument serves two functions:
- It is a (more complicated but safer) escape hatch to use when the new "multiple transparent receivers" error is encountered.
- It enables SDK users to implement their own mecahnism for avoiding address linkability when shielding funds, in the interim while we do not have our own solution (https://github.com/zcash/librustzcash/issues/1201).

2024-02-28 16:49 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func proposeShielding(
The API changes for this have now been implemented, but the functional changes require FFI changes so will need to go in a separate feature branch.

2024-02-29 14:03 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
I'll resolve it as a follow up for the whole SDK, there are more instances unrelated to this issue.

2024-02-29 16:42 UTC, pacu requested changes

2024-02-29 16:42 UTC, pacu commented on Sources/ZcashLightClientKit/Model/Proposal.swift
> +public extension Proposal {
I would advise not to expose this publicly.

2024-02-29 16:59 UTC, str4d commented on Sources/ZcashLightClientKit/Model/Proposal.swift
> +public extension Proposal {
If you have a suggestion for how to avoid exposing this publicly, I'm all ears. The constraint here is Zashi iOS using TCA, which needs to be able to construct mock data to be returned from its mock implementation of the `Synchronizer` protocol for use in e.g. preview of UIs (so we can't just return something that would be an error case).

2024-02-29 17:20 UTC, pacu commented on Sources/ZcashLightClientKit/Model/Proposal.swift
> +public extension Proposal {
NOTE: I don't know which things you've tried and which ones you haven't, but there are a few things I can thing from the top of my head. I promise I'll look this deeper shortly. I might be still lacking context and this could be somewhat inaccurate or insufficient. 


### A. "Uncle bob's Clean code" approach
Treat the whole SDK as an external dependency under the principle of Bob Martin's clean code architecture. Look at the problem as you were Unstoppable or EDGE and you don't control the dependency. Wrap around it and have a shim that you Do control and use that instead. 

### B. Pointfree.co / TCA approach. 
Make proposal on the SDK Protocol. The SDK returns an implementation of it. Then use a protocol witness or a mock implementation on Zashi to provide the mocked version that you need. 

### A and B
Make a protocol on Zashi  for what the app expects of a proposal. This propocol contains a throwing `toProposal()` function. 
Make an Adapter of the SDK's Proposal type that conforms to Zashi's. 
Make a Mock implementation for testing on Zashi that throws whenever `toProposal()` is invoked.

2024-03-01 15:04 UTC, pacu commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    func proposeTransfer(
Rebased!

2024-03-06 02:55 UTC, str4d commented
[Force-pushed](https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/compare/67d564fcdc553daaa440f652f5a12f6eda44a92b..f617f17e2ab8109dddbb53cfd2050d9c8a012e85) to clean up the commits.

2024-03-06 18:34 UTC, LukasKorba commented
I tested all 5 APIs while working on adoption of this PR in Zashi. I can confirm
- deprecated Send API still works ok
- deprecated shileding API still works ok
- new proposeTransfer API works ok
- new proposeShielding API works ok
- createProposedTransactions API works ok

2024-03-07 18:04 UTC, str4d commented
Before we merge this, I'm going to add a helper method to `Proposal` to expose the number of steps, so that callers can anticipate how many events they will get from the async stream returned from `createProposedTransactions`.

2024-03-08 00:40 UTC, nuttycom approved these changes
cursory utACK, modulo @pacu's comments

2024-03-08 00:44 UTC, nuttycom approved these changes
re-utACK 72acbc6700df62e76bdb1deb016610b445c828a7

2024-03-08 10:03 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        return AsyncThrowingStream() {
It's async stream and there's very specific way how to work with it. The stream emits values until it finishes (nil value). And a client awaits it until the nil is emitted (or an error in case of AsyncThrowingStream - throwing means this stream can emit an error, another stream is AsyncStream which ends only when nil is emitted).

2024-03-08 14:49 UTC, str4d commented
[Force-pushed](https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/compare/72acbc6700df62e76bdb1deb016610b445c828a7..129ac4398e86a62abd73056d55c26ba947dd5ef6) to remove the 2.0.11 changelog bump, as @LukasKorba will make a few other release updates before the actual release commit.

2024-03-08 14:50 UTC, merged