Update to zcash-light-client-ffi version 0.8.0.
Electric-Coin-Company/zcash-swift-wallet-sdk pull request #1417
Opened 2024-04-17 22:20 UTC by nuttycom

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-04-17 22:24 UTC, str4d requested changes
Reviewed 55cc320ac18fa6beb6252c2b8242dc3d97a46e55

2024-04-17 22:24 UTC, str4d commented on Package.swift
> +        .package(url: "https://github.com/zcash-hackworks/zcash-light-client-ffi", from: "0.8.0")
Because Swift SemVer is annoying, keep this as before:
```suggestion
        .package(url: "https://github.com/zcash-hackworks/zcash-light-client-ffi", exact: "0.8.0")
```

2024-04-17 22:24 UTC, str4d commented on CHANGELOG.md
> +  the shielded pool for the decrypted output.
This is internal to the SDK; doesn't need to be mentioned in the changelog.
```suggestion
```

What _does_ need to be mentioned is:
- The change to add Orchard receivers to the default UAs.
- The fix for XCode 15.3.

2024-04-17 23:05 UTC, nuttycom commented on CHANGELOG.md
> +  the shielded pool for the decrypted output.
Hm, so it isn't exposed anywhere?

2024-04-17 23:11 UTC, str4d commented on CHANGELOG.md
> +  the shielded pool for the decrypted output.
It should be considered internal. I don't actually know if Swift enforces that though; I vaguely recall @LukasKorba saying there are limitations there. But it's not intentionally part of the public API that people should be calling directly.

2024-04-17 23:22 UTC, nuttycom commented on CHANGELOG.md
> +  the shielded pool for the decrypted output.
The thing is, if nothing is calling it, is that whole thing just dead code at this point?

2024-04-17 23:23 UTC, str4d approved these changes
utACK 0cf08c6a59613230deb9bce881bc6161962ed82f

2024-04-18 00:34 UTC, daira approved these changes
utACK

2024-04-18 10:48 UTC, LukasKorba approved these changes

2024-04-18 13:27 UTC, merged