[#1452] TX Resubmission-the wallet has to periodically resubmit unmined transactions
Electric-Coin-Company/zcash-swift-wallet-sdk pull request #1454
Opened 2024-06-26 09:43 UTC by LukasKorba

- changelog updated
- The Compact block processor's state machine has been extended to check whether there are any unmined and unexpired transactions, and it attempts to resubmit such transactions every 5 minutes.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-06-27 07:48 UTC, HonzaR approved these changes
utACK. I just left two comments inline. Other than that, I see some lint warnings, which we could resolve in a separate PR as they seem unrelated to these changes.

2024-06-27 07:48 UTC, HonzaR commented on Sources/ZcashLightClientKit/Block/Actions/TxResubmissionAction.swift
> +                            logger.info("TxResubmissionAction trying to resubmit transaction")
Just a suggestion that applies to the below failed state log, too. I'd add a transaction identifier (like height, or so) to the log so you know which attempted trx was successful and which failed.

2024-06-27 07:48 UTC, HonzaR commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +            .filter(
The `.filter()` filters out the result, right? Otherwise, we'd need the opposite.

2024-06-27 07:50 UTC, LukasKorba commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +            .filter(
It's the opposite, filter says which are involved.

2024-07-01 18:00 UTC, daira commented on Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
> +    static let port: Int = 443
This should probably have been a separate PR. It's fine, but please say in the PR description that it changes this as well.

2024-07-01 18:02 UTC, daira commented on Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
>                  loggerProxy.error("SEND FAILED: \(error)")
```suggestion
                loggerProxy.error("SEND FAILED: \(error)")
                KRProgressHUD.dismiss()
                fail(error)
```
Log failures before doing other things.

2024-07-02 06:57 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Actions/TxResubmissionAction.swift
> +                            logger.info("TxResubmissionAction trying to resubmit transaction")
Added height, thx

2024-07-02 06:58 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/DemoAppConfig.swift
> +    static let port: Int = 443
Added to the desc.

2024-07-02 06:59 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
>                  loggerProxy.error("SEND FAILED: \(error)")
Updated the code with one more instance a few lines above it.

2024-07-02 16:03 UTC, HonzaR approved these changes
utACK. The only concern I have is that the current Zashi wallet UX prompts users with a trx submission error and still keeps them on the Send.Confirmation screen, which could lead users to retry the trx confirmation. This new feature might potentially successfully resubmit the first failed one later, resulting in two transactions. We could rethink this Zashi UX when adopting the updated SDK version.

2024-07-02 16:32 UTC, str4d requested changes
Reviewed de9b8b5917ec226757422912b6306afcce48836c

2024-07-02 16:32 UTC, str4d commented on Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift
> +            await context.update(state: .txResubmission)
Update `docs/cbp_state_machine.puml` to reflect the changes to the state machine in this PR.

2024-07-02 16:32 UTC, str4d commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +            .order((ZcashTransaction.Overview.Column.minedHeight ?? BlockHeight.max).desc)
We immediately filter on `minedHeight == nil`, so AFAICT this ordering does nothing.
```suggestion
```

2024-07-03 11:25 UTC, LukasKorba commented on Sources/ZcashLightClientKit/DAO/TransactionDao.swift
> +            .order((ZcashTransaction.Overview.Column.minedHeight ?? BlockHeight.max).desc)
Removed

2024-07-03 11:35 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Actions/EnhanceAction.swift
> +            await context.update(state: .txResubmission)
Done, both puml and png files have been updated.

2024-07-03 12:30 UTC, str4d approved these changes
utACK 85c7834152b1f89d1043b0a0aac97d5ade2eb982

2024-07-03 12:32 UTC, merged