refresh-rates
Electric-Coin-Company/zcash-swift-wallet-sdk pull request #1470
Opened 2024-07-31 12:57 UTC by LukasKorba

- API refactored to Combine's CurrentValueSubject

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-07-31 13:12 UTC, pacu approved these changes

2024-07-31 15:57 UTC, str4d requested changes

2024-07-31 15:57 UTC, str4d commented on Sources/ZcashLightClientKit/Model/FiatCurrencyResult.swift
> +    public let timestamp: TimeInterval
[The documentation for `TimeInterval`](https://developer.apple.com/documentation/foundation/timeinterval) says:
> On its own, a time interval does not specify a unique point in time, or even a span between specific times. Combining a time interval with one or more known reference points yields a [Date](https://developer.apple.com/documentation/foundation/date) or [DateInterval](https://developer.apple.com/documentation/foundation/dateinterval) value.

Should this not therefore be a `Date`, given that it is intended to convey the time at which the rate was received?

2024-07-31 15:57 UTC, str4d commented on Sources/ZcashLightClientKit/CombineSynchronizer.swift
> +    func getExchangeRateUSD() -> SinglePublisher<FiatCurrencyResult?, Never>
If `Synchronizer.getExchangeRateUsd()` is being replaced with `Synchronizer.refreshExchangeRateUSD()`, don't we need to do the same here? Otherwise how does a `CombineSynchronizer` user refresh the rate?

2024-07-31 15:57 UTC, str4d commented on Sources/ZcashLightClientKit/ClosureSynchronizer.swift
> +    func getExchangeRateUSD(completion: @escaping (Result<FiatCurrencyResult?, Error>) -> Void)
Ditto

2024-07-31 15:57 UTC, str4d commented on CHANGELOG.md
>    Coinbase, and Gemini.
Based on the changes in this PR to `Synchronizer`, this needs updating:
```suggestion
- `Synchronizer.exchangeRateUSDSubject() -> CurrentValueSubject<FiatCurrencyResult?, Never>`,
  which returns the currently-cached USD/ZEC exchange rate, or `nil` if it has not yet been
  fetched.
- `Synchronizer.refreshExchangeRateUSD()`, which refreshes the rate returned by
  `Synchronizer.exchangeRateUSDSubject()`. Prices are queried over Tor (to hide the wallet's
  IP address).
```
(I've removed the specific exchanges as we now fetch from more than these, and will alter the exchanges over time if needed.)

2024-07-31 15:57 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func exchangeRateUSDSubject() -> CurrentValueSubject<FiatCurrencyResult?, Never>
Is it normal in Swift APIs to include `Subject` in the name of a method that returns `CurrentValueSubject`?

2024-07-31 15:57 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer.swift
>      /// Fetches the latest ZEC-USD exchange rate.
```suggestion
    /// Fetches the latest ZEC-USD exchange rate and updates `exchangeRateUSDSubject`.
```

2024-07-31 15:57 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// Returns the combine's subject for exchange rate, when subscribed to it, the value is returned.
What does "the combine's subject" mean here? `Synchronizer` is usable independently of `CombineSynchronizer` AFAIK, and we also have `ClosureSynchronizer`.

I think this should read something more like:
```suggestion
    /// The latest known USD/ZEC exchange rate, paired with the time it was queried.
    ///
    /// The rate can be initialized and refreshed by calling `refreshExchangeRateUSD`.
```
(with additional details if necessary about being able to subscribe to this, if that's how this API works).

2024-08-01 08:27 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Model/FiatCurrencyResult.swift
> +    public let timestamp: TimeInterval
It's very common to use TimeInterval instead of dates, anyone who would need a Date for some reason could instantiate it with `init(timeIntervalSince1970: TimeInterval)`. However it's probably more universal to leave it a Date because of the open source code. Updated to Date.

2024-08-01 08:44 UTC, LukasKorba commented on Sources/ZcashLightClientKit/ClosureSynchronizer.swift
> +    func getExchangeRateUSD(completion: @escaping (Result<FiatCurrencyResult?, Error>) -> Void)
I reworked it so there's only a `func refreshExchangeRateUSD()` as a public API. The stream itself is a computed property, same approach that we used for events and state streams.

2024-08-01 08:45 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func exchangeRateUSDSubject() -> CurrentValueSubject<FiatCurrencyResult?, Never>
Yes, depending on the type of the variable. I changed it so there's no function anymore but we use the postfixes throughout the SDK a lot. Example:

```swift
    private let eventSubject = PassthroughSubject<SynchronizerEvent, Never>()
    public var eventStream: AnyPublisher<SynchronizerEvent, Never> { eventSubject.eraseToAnyPublisher() }

```

2024-08-01 08:46 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
>      /// Fetches the latest ZEC-USD exchange rate.
This has been removed completely.

2024-08-01 08:50 UTC, LukasKorba commented on CHANGELOG.md
>    Coinbase, and Gemini.
Updated the changelog accordingly, but the API is slightly different.

2024-08-01 11:33 UTC, str4d approved these changes
utACK

2024-08-01 11:34 UTC, merged

2024-08-06 16:34 UTC, daira commented on Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
> +        refreshExchangeRateUSDCallsCount += 1
Can this overflow?

2024-08-06 16:39 UTC, daira commented on Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
> +    var refreshExchangeRateUSDCallsCount = 0
This looks like it will infer `Int`, which is `Int64` on a 64-bit platform. It's preferable to explicitly declare `Int64` (in which case we could reasonably assume there will be no overflow).

2024-08-06 16:40 UTC, daira commented on CHANGELOG.md
> +  IP address).
Reminder that invalidating stale rates is required before release.

2024-08-06 16:40 UTC, daira reviewed
Post-hoc ACK with comments.

2024-08-07 06:11 UTC, LukasKorba commented on Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
> +        refreshExchangeRateUSDCallsCount += 1
This is autogenerated file for the purpose of mocking, done by 3rd party library. We have no control over results. To you question, this counter is used to measure how many times the methid has been called, so theoretically speaking, yes, it can overflow but typically it's used to check wheather the method has been called once or more than once.

2024-08-07 06:12 UTC, LukasKorba commented on Tests/TestUtils/Sourcery/GeneratedMocks/AutoMockable.generated.swift
> +    var refreshExchangeRateUSDCallsCount = 0
This is autogenerated file for the purpose of mocking, done by 3rd party library. We have no control over results.

2024-08-07 06:12 UTC, LukasKorba commented on CHANGELOG.md
> +  IP address).
Staleness is handled by Zashi itself at the moment.