[#1466] Choose the best server by testing responses from multiple hosts
Electric-Coin-Company/zcash-swift-wallet-sdk pull request #1472
Opened 2024-08-07 06:37 UTC by LukasKorba

- `evaluateBestOf(endpoints)` async method implemented. It takes a list of endpoints and evaluates the performance of each, rule out some during the process and returns top `k` best servers.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-08-07 16:09 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                if let localBranch = await blockProcessor.consensusBranchIdFor(Int32(info.blockHeight)) {
```suggestion
                if let localBranchID = await blockProcessor.consensusBranchIdFor(Int32(info.blockHeight)) {
```

2024-08-07 16:09 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                    guard remoteBranchID == localBranch else {
```suggestion
                    guard remoteBranchID == localBranchID else {
```

2024-08-22 08:15 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/Test Servers/TestServersViewController.swift
> +    ]
This is an independent list, I made a new section in the demo app to demonstrate how to use the new public API. It has nothing to do with Zashi, we purposely don't hardcode servers to the SDK.

2024-08-27 07:23 UTC, Milan-Cerovsky approved these changes

2024-08-27 11:25 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                    let mean = (getInfoTime + latestBlockHeightTime) / 2
This is equivalent to `(endTime - startTime) / 2` (in which case `markTime` can be deleted).

2024-08-27 11:55 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        latencyThreshold: Double = 300.0,
```suggestion
        latencyThresholdMillis: Double = 300.0,
```

2024-08-27 11:58 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                if let localBranchID = await blockProcessor.consensusBranchIdFor(Int32(info.blockHeight)) {
```suggestion
                guard let localBranchID = await blockProcessor.consensusBranchIdFor(Int32(info.blockHeight)) else {
                    continue
                }
```
(Just a style issue, non-blocking.)

2024-08-27 12:03 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                guard info.blockHeight + 100 >= info.estimatedHeight else {
Note that `estimatedHeight` is not necessarily accurate.

2024-08-27 12:06 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            }
Filtering before sorting is slightly more efficient. It probably doesn't matter though.

2024-08-27 13:23 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                    let mean = (getInfoTime + latestBlockHeightTime) / 2
True, the final mean could be computed that way but I report times of `getInfo()` and `latestBlockHeight()` separately. See

```swift
let startTime = Date().timeIntervalSince1970
let info = try? await service.service.getInfo()
let markTime = Date().timeIntervalSince1970
let latestBlockHeight = try? await service.service.latestBlockHeight()
let endTime = Date().timeIntervalSince1970
```

and

```swift
return CheckResult(
    id: service.url,
    info: info,
    getInfoTime: getInfoTime,
    latestBlockHeight: latestBlockHeight,
    latestBlockHeightTime: latestBlockHeightTime,
    mean: mean,
    service: service,
    blockTime: 0
)
```

2024-08-27 13:25 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        latencyThreshold: Double = 300.0,
Updated

2024-08-27 13:27 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                if let localBranchID = await blockProcessor.consensusBranchIdFor(Int32(info.blockHeight)) {
Updated

2024-08-27 13:30 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            }
True, the list is so small the effect is not going to be measurable that much but I swapped those operations anyway.

2024-09-02 15:33 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                guard info.blockHeight + 100 >= info.estimatedHeight else {
What is `nBlocks` here?

Since we just don't know the tip height and `estimatedHeight` could be wildly inaccurate, I would only try to rule out servers that are extremely broken, i.e. definitely stuck or on the wrong chain. zcashd comes out of "sync" (which it calls "initial block download") 24 hours before the estimated tip (`DEFAULT_MAX_TIP_AGE` seconds), but that's historical and I think unnecessarily conservative. 6 hours or 288 blocks should be sufficient I think.

2024-09-03 19:49 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                guard info.blockHeight + 100 >= info.estimatedHeight else {
Yes, although I would use a named constant instead of hardcoding 288.

2024-09-03 20:07 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        nBlocks: Int = 100,
It's not documented what `nBlocks` is. Separately, I recommended 288 blocks (6 hours) for the "correctly synced" threshold.

2024-09-03 20:15 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                // rule out syncing server
```suggestion
                // Rule out servers that are syncing, stuck, or probably on the wrong fork.
                // To avoid falsely ruling out all servers this can only be a very loose check
                // (i.e. `nBlocks` should not be too small), because `info.estimatedHeight`
                // may be quite inaccurate.
```
(Replace `nBlocks` with the new name if it is renamed.)

2024-09-03 20:16 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            let sortedUnderThreshold = tmpResults.compactMap {
```suggestion
            let underThreshold = tmpResults.compactMap {
```
This is no longer sorted given that the order of operations was swapped.

2024-09-03 20:19 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            let sortedServers = sortedUnderThreshold.sorted {
```suggestion
            let sortedUnderThreshold = underThreshold.sorted {
```
Swapping the order of operations was done incorrectly; `sortedServers` was not used. This fixes it.

2024-09-03 20:21 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                // rule out servers that can't fetch N blocks under the fetchThreshold
Say 100 blocks here or define N as a constant.

2024-09-03 20:22 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        fetchThresholdSeconds: Double = 60.0,
Document that this is a maximum for the time to fetch 100 blocks.

2024-09-03 20:26 UTC, daira requested changes
The fix to the server sorting is blocking.

2024-09-04 05:35 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                guard info.blockHeight + 100 >= info.estimatedHeight else {
updated to use the constant

2024-09-04 05:36 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        nBlocks: Int = 100,
`syncedThresholdBlocks` used and set to 288 as a default value.

2024-09-04 05:57 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                // rule out syncing server
Updated

2024-09-04 05:58 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            let sortedUnderThreshold = tmpResults.compactMap {
Updated

2024-09-04 05:59 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            let sortedServers = sortedUnderThreshold.sorted {
Updated

2024-09-04 06:11 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        fetchThresholdSeconds: Double = 60.0,
The whole method is now documented with all parameters.

2024-09-04 06:12 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                // rule out servers that can't fetch N blocks under the fetchThreshold
Updated

2024-09-04 08:27 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    ///    - fetchThresholdSeconds: The time to download 100 blocks from the stream must be below this threshold. The default is 60 seconds.
```suggestion
    ///    - fetchThresholdSeconds: The time to download `amountOfBlocksToFetch` blocks from the stream must be below this threshold. The default is 60 seconds.
```

2024-09-04 08:31 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +        nBlocks: Int,
```suggestion
        nBlocksToFetch: Int,
```

2024-09-04 08:32 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    ///    - fetchThresholdSeconds: The time to download 100 blocks from the stream must be below this threshold. The default is 60 seconds.
```suggestion
    ///    - fetchThresholdSeconds: The time to download `amountOfBlocksToFetch` blocks from the stream must be below this threshold. The default is 60 seconds.
```

2024-09-04 08:34 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    ///    - fetchThresholdSeconds: The time to download 100 blocks from the stream must be below this threshold. The default is 60 seconds.
```suggestion
    ///    - fetchThresholdSeconds: The time to download `amountOfBlocksToFetch` blocks from the stream must be below this threshold. The default is 60 seconds.
```

2024-09-04 08:35 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +        nBlocks: Int,
(`nBlocksToFetch` would also be fine for this parameter, and shorter.)

2024-09-04 09:16 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                guard info.blockHeight + ZcashSDK.syncedThresholdBlocks >= info.estimatedHeight else {
Go unsigned integers [are defined to wrap on overflow](https://go.dev/ref/spec#Integer_overflow), so this is fine.

2024-09-04 12:30 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +
```suggestion

            guard info.blockHeight >= amountOfBlocksToFetch else {
                continue
            }
```

2024-09-04 12:39 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                }
I think this doesn't match the specification at https://hackmd.io/nFVgxp_iSx-yFoxkx4Z1PA : 
> In order by lowest to highest latency, use `GetBlockRange` to fetch the most recent blocks. When the current server is taking longer than `fetch_threshold` or it is worse than $k$ other servers, abort that connection and rule out that server.

The part about early-aborting the connection if the server is taking too long isn't implemented.

2024-09-04 12:50 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +        nBlocks: Int,
Updated

2024-09-04 12:51 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    ///    - fetchThresholdSeconds: The time to download 100 blocks from the stream must be below this threshold. The default is 60 seconds.
Updated

2024-09-04 12:51 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    ///    - fetchThresholdSeconds: The time to download 100 blocks from the stream must be below this threshold. The default is 60 seconds.
Updated

2024-09-04 12:52 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                    let info = try? await service.service.getInfo()
If there's an error or timeout from the call, what happens? We want only the server that errored / timed out to be excluded.

2024-09-04 12:53 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +
Added

2024-09-04 12:53 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                }
Implemented the termination part.

2024-09-04 21:27 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                    let info = try? await service.service.getInfo()
What does `try? await ...` mean? I cannot find the word `try` at all in the [Go language specification](https://go.dev/ref/spec).

2024-09-05 06:13 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                        break
Note that there was a [bug report about iterator cleanup](https://forums.swift.org/t/asyncsequence-break-and-cancellation/52787/21) when `break` is used within `for [try] await`. The actual bug ticket, "FB9700937 (break in async for loop does not cancel an async sequence)", appears to have been submitted to the Apple feedback system which is not public, so I don't know whether it was a real bug or whether it was fixed.

2024-09-05 06:24 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                // rule out servers that can't fetch 100 blocks under fetchThresholdSeconds
```suggestion
                // rule out servers that can't fetch nBlocksToFetch blocks under fetchThresholdSeconds
```

2024-09-05 06:29 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                let endTime = Date().timeIntervalSince1970
Note that there was a [bug report about iterator cleanup](https://forums.swift.org/t/asyncsequence-break-and-cancellation/52787/21) when `break` is used within `for [try] await`. The actual bug ticket, "FB9700937 (break in async for loop does not cancel an async sequence)", appears to have been submitted to the Apple feedback system which is not public (bad :green_apple:!), so I don't know whether it was a real bug or whether it was fixed :frowning_face:.

In any case, if `break` within `for try await` only breaks successfully from the sequence, then the code relies on `Date().timeIntervalSince1970` being monotonic so that a timeout within a loop is guaranteed to imply that `blockTime < fetchThresholdSeconds` is false. In order to not rely on that, it might be better to do something like:

```suggestion
                var endTime = startTime;
                for try await block in stream {
                    endTime = Date().timeIntervalSince1970
                    if endTime - startTime >= fetchThresholdSeconds {
                        break
                    }
                }

                let blockTime = endTime - startTime
```

2024-09-05 06:37 UTC, daira requested changes
At least the fix to the comment is blocking.

2024-09-05 06:38 UTC, daira approved these changes
Actually, since I'm going on PTO and might not be able to review this again for a while, I'll give an approving review just to avoid blocking merge.

2024-09-05 06:44 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                // rule out servers that can't fetch 100 blocks under fetchThresholdSeconds
Updated

2024-09-05 06:47 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                let endTime = Date().timeIntervalSince1970
Updated

2024-09-05 08:24 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                endTime = Date().timeIntervalSince1970
This still has the problem of assuming monotonicity. In my suggestion this line was deleted, so that `endTime` is still the value set on line 808 in the last iteration of the loop. That way, whenever the loop breaks early on line 810, `blockTime < fetchThresholdSeconds` will be false and we are guaranteed not to incorrectly set `value.blockTime` to the time for a smaller number of blocks.

An alternative would be to directly continue the outer loop over `checkResults` stating on line 791; I don't know whether Swift supports labelled `continue`, though. (In, say, Java, you could label that loop and say `continue <label>;`.) Or you can simulate that by setting a flag.

2024-09-05 08:30 UTC, daira submitted a review, later dismissed
See comment.

2024-09-05 09:26 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                endTime = Date().timeIntervalSince1970
Got it, removed.

2024-09-06 07:45 UTC, merged

2024-09-06 07:54 UTC, LukasKorba commented
FYI, I forgot to commit the final change requested with removing 1 line. So I made it right after in this [PR](https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/pull/1484), sorry.