[#1511] Refactor account representation from int to a dedicated account structure
Electric-Coin-Company/zcash-swift-wallet-sdk pull request #1515
Opened 2024-11-22 14:23 UTC by LukasKorba

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-11-22 14:55 UTC, pacu commented on Sources/ZcashLightClientKit/Account/Account.swift
> +public struct Zip32Account: Equatable, Codable, Hashable {
This is a much needed change!

2024-11-22 14:58 UTC, pacu requested changes

2024-11-22 14:58 UTC, pacu commented on Sources/ZcashLightClientKit/Account/Account.swift
> +    public let index: Int32
I would take the opportunity to make this UInt32 and internally then convert to Int32.

Also I the derivation tool in the FFI derives the Network Id as UInt32 when `u32` is specified in Rust, so we could make that change later. 

If the public API uses UInt32 then this change in Rust won't imply a deprecation in the SDK's public API. then the init can get rid of the `fatalError()` call.

2024-11-23 14:41 UTC, daira commented on Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift
> +        let account = Zip32Account(0)
Even though this is only sample code, I'd suggest making this an attribute of `SendViewController` so that it's only hardcoded once. (There's no need to do anything more than that.)

2024-11-23 14:53 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +    public let index: Int32
The valid range is `0..<(1<<31)`, so it doesn't really matter from that point of view whether it is stored as `Int32` or `UInt32`. On the other hand, `librustzcash` uses `u32` as you say, so I'm in favour of this change.

2024-11-23 14:57 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +        }
```suggestion
    public init(_ index: UInt32) {
        guard index < (1<<31) else {
            fatalError("Account index must be less than 2^31. Input value is \(index).")
        }
```

2024-11-23 15:08 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +public struct AccountId: Equatable, Codable, Hashable {
I would prefer this to be called `LocalAccountId`.

2024-11-23 15:09 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +            fatalError("Account index must be >= 0. Input value is \(index).")
```suggestion
            fatalError("Local account id must be >= 0. Input value is \(index).")
```

2024-11-23 15:09 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +    public let index: Int
```suggestion
    public let id: Int
```

2024-11-23 15:13 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +    }
```suggestion
    /// - Parameters:
    ///     - id: the local account id, which must be nonnegative.
    public init(_ id: Int) {
        guard id >= 0 else {
            fatalError("Local account id must be >= 0. Input value is \(id).")
        }
        
        self.id = id
    }
```

2024-11-23 15:15 UTC, daira commented on Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift
> +        // TODO: This is hardcoded Zip32Account for index 0, must be updated
Please file an issue like the lint says.

2024-11-23 15:16 UTC, daira commented on Sources/ZcashLightClientKit/Entity/SentNoteEntity.swift
> +    var fromAccount: AccountId { get }
```suggestion
    var fromAccount: LocalAccountId { get }
```

2024-11-23 15:17 UTC, daira commented on Sources/ZcashLightClientKit/Entity/SentNoteEntity.swift
> +    var toAccount: AccountId? { get }
```suggestion
    var toAccount: LocalAccountId? { get }
```

2024-11-23 16:24 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
>      func deriveUnifiedSpendingKey(from seed: [UInt8], accountIndex: Int32) throws -> UnifiedSpendingKey
```suggestion
    /// - Parameter account: account that the key can spend from
    /// - Throws: `rustDeriveUnifiedSpendingKey` if rust layer returns error.
    func deriveUnifiedSpendingKey(from seed: [UInt8], account: LocalAccountId) throws -> UnifiedSpendingKey
```

2024-11-23 16:26 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
> +    ///     - `derivationToolInvalidAccount` if the `account.index` is invalid.
I think this error cannot occur here; please check.
```suggestion
```

2024-11-23 16:27 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
> +    /// - Parameter accountIndex: `Int32` with the account number
```suggestion
    /// - Parameter account: the account to derive a key for
```

2024-11-23 16:27 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
> +    ///     - `derivationToolInvalidAccount` if the `account.index` is invalid.
```suggestion
    ///     - `derivationToolInvalidAccount` if the account ID is invalid.
```

2024-11-23 16:52 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +    public init(_ index: Int32) {
```suggestion
    /// - Parameter index: the ZIP 32 account index, which must be nonnegative.
    public init(_ index: Int32) {
```

2024-11-23 17:17 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +        }
```suggestion
    /// - Parameter index: the ZIP 32 account index, which must be less than ``1<<31``.
    public init(_ index: UInt32) {
        guard index < (1<<31) else {
            fatalError("Account index must be less than 1<<31. Input value is \(index).")
        }
```

2024-11-23 17:21 UTC, daira commented on Sources/ZcashLightClientKit/Entity/AccountEntity.swift
> +        hasher.combine(account.index)
Changing the type causes no problem here.

2024-11-23 17:21 UTC, daira commented on Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
> +        public let accountId: AccountId
```suggestion
        public let accountId: LocalAccountId
```

2024-11-23 17:21 UTC, daira commented on Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
> +        public let fromAccount: AccountId?
```suggestion
        public let fromAccount: LocalAccountId?
```

2024-11-23 17:24 UTC, daira commented on Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
> +                fromAccount = AccountId(accountId)
```suggestion
                fromAccount = LocalAccountId(accountId)
```

2024-11-23 17:24 UTC, daira commented on Sources/ZcashLightClientKit/Entity/TransactionEntity.swift
> +            self.accountId = AccountId(try row.get(Column.accountId))
```suggestion
            self.accountId = LocalAccountId(try row.get(Column.accountId))
```

2024-11-23 17:29 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            accounts.append(Zip32Account(Int32(account.account_index)))
```suggestion
            accounts.append(Zip32Account(account.account_index))
```

2024-11-23 17:29 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
```suggestion
            Int32(account.index),
```

2024-11-23 17:31 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
```suggestion
            Int32(account.index),
```

2024-11-23 17:35 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
>          }
```suggestion
        precondition(account.index < (1<<31));
```

2024-11-23 17:42 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
It's no longer necessary to check that `account.index` is in range, because that is ensured by the `Zip32Account` constructor. Also, delete all occurrences of `ZcashError.rustGetTransparentBalanceNegativeAccount` since it can no longer happen.

```suggestion
```

2024-11-23 17:44 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index
```suggestion
            Int32(account.index)
```

2024-11-23 17:45 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Also delete all occurrences of `rustGetVerifiedTransparentBalanceNegativeAccount`.

```suggestion
```

2024-11-23 17:45 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
```suggestion
            Int32(account.index),
```

2024-11-23 17:46 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
```suggestion
            Int32(account.index),
```

2024-11-23 17:54 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
```suggestion
            Zip32Index(account.index),
```

2024-11-23 18:09 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
>      /// - Parameter memo: the `MemoBytes` for this transaction. pass `nil` when sending to transparent receivers
On lines 212, 229, and 246, the description should be "the given ZIP 32 account" rather than "index of the given account".

2024-11-23 18:11 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// Attempts to propose fulfilling a [ZIP-321](https://zips.z.cash/zip-0321) payment URI using the given `account.index`
```suggestion
    /// Attempts to propose fulfilling a [ZIP-321](https://zips.z.cash/zip-0321) payment URI using the given ZIP 32 account.
```

2024-11-23 18:12 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    ///  - Parameter account: the account index that allows spends to occur.
```suggestion
    ///  - Parameter account: the ZIP 32 account providing spend authority.
```

2024-11-23 18:17 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    public func getAccountBalance(account: Zip32Account = Zip32Account(0)) async throws -> AccountBalance? {
Since the type is changing incompatibly anyway, I would just take the opportunity to remove the default.
```suggestion
    public func getAccountBalance(account: Zip32Account) async throws -> AccountBalance? {
```

2024-11-23 18:18 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        try await initializer.rustBackend.getWalletSummary()?.accountBalances[UInt32(account.index)]
```suggestion
        try await initializer.rustBackend.getWalletSummary()?.accountBalances[account.index]
```

2024-11-23 18:19 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      /// Given the seed bytes tand the account index, return the UnifiedSpendingKey
```suggestion
    /// Given the seed bytes and ZIP 32 account index, return the corresponding UnifiedSpendingKey.
```

2024-11-23 18:20 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    /// - Parameter accountIndex: `Int32` with the account number
```suggestion
    /// - Parameter account: the ZIP 32 account
```

2024-11-23 18:20 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func deriveUnifiedSpendingKey(seed: [UInt8], accountIndex: Int32) throws -> UnifiedSpendingKey
```suggestion
    func deriveUnifiedSpendingKey(seed: [UInt8], account: Zip32Account) throws -> UnifiedSpendingKey
```

2024-11-23 18:21 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      ///     - `derivationToolInvalidAccount` if the `accountIndex` is invalid.
```suggestion
```

2024-11-23 18:21 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    /// - Parameter accountIndex: `Int32` with the account number
```suggestion
    /// - Parameter account: the ZIP 32 account
```

2024-11-23 18:22 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      ///     - `derivationToolInvalidAccount` if the `accountIndex` is invalid.
```suggestion
```

2024-11-23 18:41 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      ///     - `derivationToolInvalidAccount` if the `accountIndex` is invalid.
This can't happen given the type change below. Remove the error if there are no more occurrences.
```suggestion
```

2024-11-23 18:42 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func deriveArbitraryAccountKey(contextString: [UInt8], seed: [UInt8], accountIndex: Int32) throws -> [UInt8]
```suggestion
    func deriveArbitraryAccountKey(contextString: [UInt8], seed: [UInt8], account: Zip32Account) throws -> [UInt8]
```

2024-11-23 18:45 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>          return try backend.deriveArbitraryAccountKey(contextString: contextString, from: seed, accountIndex: accountIndex)
```suggestion
    public func deriveArbitraryAccountKey(contextString: [UInt8], seed: [UInt8], account: Zip32Account) throws -> [UInt8] {
        return try backend.deriveArbitraryAccountKey(contextString: contextString, from: seed, account: account)
```

2024-11-23 18:49 UTC, daira commented on Sources/ZcashLightClientKit/Account/Account.swift
> +public struct Zip32Account: Equatable, Codable, Hashable {
I think we should make it clearer that this is a ZIP 32 account *index*. That is, ...
```suggestion
/// A [ZIP 32](https://zips.z.cash/zip-0032) account *index*.
///
/// Note that this must be paired with a seed (or other context that
/// specifies a seed) in order to identify a ZIP 32 *account*.
public struct Zip32AccountIndex: Equatable, Codable, Hashable {
```

2024-11-23 18:54 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
>      /// Derives and returns a unified spending key from the given seed for the given account ID.
```suggestion
    /// Derives and returns a unified spending key from the given seed and ZIP 32 account index.
```

2024-11-23 19:01 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
It's no longer necessary to check that the index is in range, because that is ensured by the `Zip32AccountIndex` constructor. Also, delete all occurrences of `rustGetTransparentBalanceNegativeAccount` since it can no longer happen.

```suggestion
    func getTransparentBalance(accountIndex: Zip32AccountIndex) async throws -> Int64 {
```

2024-11-23 19:03 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Also delete all occurrences of `rustGetVerifiedTransparentBalanceNegativeAccount`.

```suggestion
    func getVerifiedTransparentBalance(accountIndex: Zip32AccountIndex) async throws -> Int64 {
```

2024-11-23 19:05 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
>      /// Returns a list of the accounts in the wallet.
```suggestion
    /// Returns a list of the ZIP 32 indices of accounts in the wallet.
```

2024-11-23 19:05 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    func listAccounts() async throws -> [Zip32Account]
```suggestion
    func listAccounts() async throws -> [Zip32AccountIndex]
```

2024-11-23 19:08 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter account: the account whose address is of interest. By default, the first account is used.
```suggestion
    /// - Parameter accountIndex: the ZIP 32 index of the account whose address is of interest.
```

2024-11-23 19:08 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func getSaplingAddress(account: Zip32Account) async throws -> SaplingAddress
```suggestion
    func getSaplingAddress(accountIndex: Zip32AccountIndex) async throws -> SaplingAddress
```

2024-11-23 19:18 UTC, daira commented on Sources/ZcashLightClientKit/ClosureSynchronizer.swift
> +    /// - Parameter account: the account from which to transfer funds.
```suggestion
    /// - Parameter accountIndex: the ZIP 32 index of the account from which to transfer funds.
```
and the same wording for every similar case.

2024-11-23 19:18 UTC, daira commented on Sources/ZcashLightClientKit/ClosureSynchronizer.swift
> +        account: Zip32Account,
```suggestion
        accountIndex: Zip32AccountIndex,
```
and every similar case.

2024-11-23 19:26 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter account: the account whose address is of interest. By default, the first account is used.
```suggestion
    /// - Parameter accountIndex: the ZIP 32 index of the account whose address is of interest.
```
There is no default for this parameter.

2024-11-23 19:26 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter account: the account whose address is of interest. By default, the first account is used.
```suggestion
    /// - Parameter accountIndex: the ZIP 32 index of the account whose address is of interest.
```
There is no default for this parameter.

2024-11-23 19:29 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
```suggestion
```

2024-11-23 19:30 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        guard let tBalance = try await self.getAccountBalance(account: account)?.unshielded else {
```suggestion
        guard let tBalance = try await self.getAccountBalance(accountIndex: spendingKey.accountIndex)?.unshielded else {
```

2024-11-23 19:31 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        guard let tBalance = try await self.getAccountBalance(account: account)?.unshielded else {
Revert this.

2024-11-23 19:33 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        let account = Zip32Account(Int32(spendingKey.account))
```suggestion
        let accountIndex = spendingKey.accountIndex
```
(I am going to also suggest renaming `UnifiedSpendingKey.index` and changing its type to `Zip32AccountIndex` so that this works.)

2024-11-23 19:34 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            account: account,
```suggestion
            accountIndex: accountIndex,
```

2024-11-23 19:34 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                account: Zip32Account(Int32(spendingKey.account)),
```suggestion
                accountIndex: spendingKey.accountIndex,
```

2024-11-23 19:40 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      /// supported so the default value of 1 is recommended.
Please check that this is correct.
```suggestion
    /// - Parameter accountIndex: the ZIP 32 index of the account
```

2024-11-23 19:41 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +
```suggestion
    public func deriveUnifiedSpendingKey(seed: [UInt8], accountIndex: Zip32AccountIndex) throws -> UnifiedSpendingKey {
```

2024-11-23 19:42 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    ///     - `derivationToolInvalidAccount` if the `account` is invalid.
```suggestion
```

2024-11-23 19:43 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +
```suggestion
    public func deriveArbitraryAccountKey(contextString: [UInt8], seed: [UInt8], accountIndex: Zip32AccountIndex) throws -> [UInt8] {
```

2024-11-23 19:44 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    ///     - `derivationToolInvalidAccount` if the `account` is invalid.
```suggestion
```

2024-11-23 19:45 UTC, daira commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    /// - Parameter accountIndex: `Int32` with the account number
```suggestion
    /// - Parameter accountIndex: the ZIP 32 index of the account
```

2024-11-23 19:46 UTC, daira commented on Tests/DarksideTests/PaymentURIFulfillmentTests.swift
> +                account: Account(0)
```suggestion
                accountIndex: Zip32AccountIndex(0)
```

2024-11-23 19:47 UTC, daira commented on Tests/DarksideTests/PaymentURIFulfillmentTests.swift
> +                account: Account(0)
```suggestion
                accountIndex: Zip32AccountIndex(0)
```

2024-11-23 19:47 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        let account = Account(0)
```suggestion
        let accountIndex: Zip32AccountIndex(0)
```

2024-11-23 19:47 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        var initialTransparentBalance: Zatoshi = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
```suggestion
        var initialTransparentBalance: Zatoshi = try await coordinator.synchronizer.getAccountBalance(accountIndex: accountIndex)?.unshielded ?? .zero
```

2024-11-23 19:48 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +                    initialTotalBalance = try await synchronizer.getAccountBalance(account: account)?.saplingBalance.total() ?? .zero
```suggestion
                    initialVerifiedBalance = try await synchronizer.getAccountBalance(accountIndex: accountIndex)?.saplingBalance.spendableValue ?? .zero
                    initialTotalBalance = try await synchronizer.getAccountBalance(accountIndex: accountIndex)?.saplingBalance.total() ?? .zero
```

2024-11-23 19:48 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        initialTransparentBalance = (try? await coordinator.synchronizer.getAccountBalance(account: account))?.unshielded ?? .zero
```suggestion
        initialTransparentBalance = (try? await coordinator.synchronizer.getAccountBalance(accountIndex: accountIndex))?.unshielded ?? .zero
```

2024-11-23 19:48 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        let tFundsDetectedBalance = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
```suggestion
        let tFundsDetectedBalance = try await coordinator.synchronizer.getAccountBalance(accountIndex: accountIndex)?.unshielded ?? .zero
```

2024-11-23 19:48 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        let confirmedTFundsBalance = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
```suggestion
        let confirmedTFundsBalance = try await coordinator.synchronizer.getAccountBalance(accountIndex: accountIndex)?.unshielded ?? .zero
```

2024-11-23 19:49 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        let postShieldingBalance = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
```suggestion
        let postShieldingBalance = try await coordinator.synchronizer.getAccountBalance(accountIndex: accountIndex)?.unshielded ?? .zero
```

2024-11-23 19:49 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        let postShieldingShieldedBalance = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
```suggestion
        let postShieldingShieldedBalance = try await coordinator.synchronizer.getAccountBalance(accountIndex: accountIndex)?.unshielded ?? .zero
```

2024-11-23 19:49 UTC, daira commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        let postShieldingConfirmationShieldedBalance = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
```suggestion
        let postShieldingConfirmationShieldedBalance = try await coordinator.synchronizer.getAccountBalance(accountIndex: accountIndex)?.unshielded ?? .zero
```

2024-11-23 19:50 UTC, daira commented on Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
> +            XCTAssertEqual(account, Account(3))
```suggestion
        synchronizerMock.getSaplingAddressAccountIndexClosure = { accountIndex in
            XCTAssertEqual(accountIndex, Zip32AccountIndex(3))
```

2024-11-23 19:51 UTC, daira commented on Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
> +            XCTAssertEqual(account, testAccount)
```suggestion
        let testAccountIndex = Zip32AccountIndex(3)
        
        synchronizerMock.getSaplingAddressAccountIndexClosure = { accountIndex in
            XCTAssertEqual(accountIndex, testAccountIndex)
```
and similarly below.

2024-11-23 19:52 UTC, daira commented on Tests/OfflineTests/DerivationToolTests/DerivationToolMainnetTests.swift
> +        let spendingKey = try derivationTool.deriveUnifiedSpendingKey(seed: seedBytes, account: Account(0))
```suggestion
        let spendingKey = try derivationTool.deriveUnifiedSpendingKey(seed: seedBytes, accountIndex: Zip32AccountIndex(0))
```
and similarly below.

2024-11-23 19:53 UTC, daira commented on Tests/TestUtils/TestCoordinator.swift
> +            account: Account(0)
```suggestion
            accountIndex: Zip32AccountIndex(0)
```

2024-11-23 20:58 UTC, daira requested changes
Changes requested.

2024-11-23 21:33 UTC, str4d commented on Sources/ZcashLightClientKit/Account/Account.swift
> +public struct AccountId: Equatable, Codable, Hashable {
No, this will become _the_ account ID containing the UUID; the local one will not be visible to the Swift code.

2024-11-23 22:02 UTC, str4d commented on Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift
> +        // TODO: This is hardcoded Zip32Account for index 0, must be updated
We already have one: #1612

2024-11-23 22:03 UTC, str4d commented on Sources/ZcashLightClientKit/Entity/SentNoteEntity.swift
> +    var fromAccount: AccountId { get }
No, per my above comment (it would just get renamed back in the next PR).

2024-11-25 08:33 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Account/Account.swift
> +    public let index: Int32
Updated

2024-11-25 08:39 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Account/Account.swift
> +    public let index: Int
Updated

2024-11-25 08:44 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Block/Actions/SaplingParamsAction.swift
> +        // TODO: This is hardcoded Zip32Account for index 0, must be updated
Updated

2024-11-25 08:45 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Entity/SentNoteEntity.swift
> +    var fromAccount: AccountId { get }
Skipped

2024-11-25 08:45 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Account/Account.swift
> +public struct AccountId: Equatable, Codable, Hashable {
Skipped

2024-11-25 08:45 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Account/Account.swift
> +    }
Updated except "Local"

2024-11-25 08:48 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
>      func deriveUnifiedSpendingKey(from seed: [UInt8], accountIndex: Int32) throws -> UnifiedSpendingKey
Updated

2024-11-25 08:50 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
> +    ///     - `derivationToolInvalidAccount` if the `account.index` is invalid.
Checked and removed.

2024-11-25 08:52 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
> +    /// - Parameter accountIndex: `Int32` with the account number
Updated

2024-11-25 08:52 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
> +    ///     - `derivationToolInvalidAccount` if the `account.index` is invalid.
Updated

2024-11-25 08:54 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Account/Account.swift
> +        }
Updated

2024-11-25 08:57 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            accounts.append(Zip32Account(Int32(account.account_index)))
Updated

2024-11-25 08:59 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
Updated

2024-11-25 08:59 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
Updated

2024-11-25 09:00 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
Updated

2024-11-25 09:00 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index
Updated

2024-11-25 09:00 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
Updated

2024-11-25 09:00 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
Updated

2024-11-25 09:01 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            account.index,
Updated

2024-11-25 09:01 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// Attempts to propose fulfilling a [ZIP-321](https://zips.z.cash/zip-0321) payment URI using the given `account.index`
Updated

2024-11-25 09:04 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    ///  - Parameter account: the account index that allows spends to occur.
Updated

2024-11-25 09:07 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        try await initializer.rustBackend.getWalletSummary()?.accountBalances[UInt32(account.index)]
Updated

2024-11-25 09:08 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      /// Given the seed bytes tand the account index, return the UnifiedSpendingKey
Updated

2024-11-25 09:08 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    /// - Parameter accountIndex: `Int32` with the account number
Updated

2024-11-25 09:08 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func deriveUnifiedSpendingKey(seed: [UInt8], accountIndex: Int32) throws -> UnifiedSpendingKey
Updated

2024-11-25 09:09 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      ///     - `derivationToolInvalidAccount` if the `accountIndex` is invalid.
Updated

2024-11-25 09:10 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    /// - Parameter accountIndex: `Int32` with the account number
Updated

2024-11-25 09:11 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      ///     - `derivationToolInvalidAccount` if the `accountIndex` is invalid.
Updated

2024-11-25 09:12 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    func deriveArbitraryAccountKey(contextString: [UInt8], seed: [UInt8], accountIndex: Int32) throws -> [UInt8]
Updated

2024-11-25 09:13 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Account/Account.swift
> +public struct Zip32Account: Equatable, Codable, Hashable {
Updated

2024-11-25 09:14 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
>      /// Derives and returns a unified spending key from the given seed for the given account ID.
Updated

2024-11-25 09:16 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Updated

2024-11-25 09:18 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
Updated

2024-11-25 09:19 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    func listAccounts() async throws -> [Zip32Account]
Updated

2024-11-25 09:19 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter account: the account whose address is of interest. By default, the first account is used.
Updated

2024-11-25 09:22 UTC, LukasKorba commented on Sources/ZcashLightClientKit/ClosureSynchronizer.swift
> +    /// - Parameter account: the account from which to transfer funds.
Updated everywhere

2024-11-25 09:23 UTC, LukasKorba commented on Sources/ZcashLightClientKit/ClosureSynchronizer.swift
> +        account: Zip32Account,
Updated everywhere

2024-11-25 09:23 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter account: the account whose address is of interest. By default, the first account is used.
Updated

2024-11-25 09:24 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
>      /// Returns a list of the accounts in the wallet.
Updated

2024-11-25 09:24 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter account: the account whose address is of interest. By default, the first account is used.
Updated

2024-11-25 09:26 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        guard let tBalance = try await self.getAccountBalance(account: account)?.unshielded else {
Updated

2024-11-25 09:27 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        let account = Zip32Account(Int32(spendingKey.account))
Updated

2024-11-25 09:27 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +            account: account,
Updated

2024-11-25 09:27 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +                account: Zip32Account(Int32(spendingKey.account)),
Updated

2024-11-25 09:28 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
>      /// supported so the default value of 1 is recommended.
Updated

2024-11-25 09:30 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +
Updated and the error removed.

2024-11-25 09:31 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    ///     - `derivationToolInvalidAccount` if the `account` is invalid.
Updated

2024-11-25 09:31 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +
Updated

2024-11-25 09:31 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    /// - Parameter accountIndex: `Int32` with the account number
Updated

2024-11-25 09:32 UTC, LukasKorba commented on Tests/DarksideTests/PaymentURIFulfillmentTests.swift
> +                account: Account(0)
Updated

2024-11-25 09:32 UTC, LukasKorba commented on Tests/DarksideTests/PaymentURIFulfillmentTests.swift
> +                account: Account(0)
Updated

2024-11-25 09:34 UTC, LukasKorba commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        var initialTransparentBalance: Zatoshi = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
Updated

2024-11-25 09:34 UTC, LukasKorba commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        initialTransparentBalance = (try? await coordinator.synchronizer.getAccountBalance(account: account))?.unshielded ?? .zero
Updatec

2024-11-25 09:34 UTC, LukasKorba commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        let tFundsDetectedBalance = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
Updated

2024-11-25 09:34 UTC, LukasKorba commented on Tests/DarksideTests/ShieldFundsTests.swift
> +        let postShieldingBalance = try await coordinator.synchronizer.getAccountBalance(account: account)?.unshielded ?? .zero
Updated

2024-11-25 09:38 UTC, LukasKorba commented on Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
> +            XCTAssertEqual(account, Account(3))
Updated

2024-11-25 09:38 UTC, LukasKorba commented on Tests/OfflineTests/CombineSynchronizerOfflineTests.swift
> +            XCTAssertEqual(account, testAccount)
Updated

2024-11-25 09:40 UTC, LukasKorba commented on Tests/OfflineTests/DerivationToolTests/DerivationToolMainnetTests.swift
> +        let spendingKey = try derivationTool.deriveUnifiedSpendingKey(seed: seedBytes, account: Account(0))
Updated

2024-11-25 09:41 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    ///     - `derivationToolInvalidAccount` if the `account` is invalid.
Updated

2024-11-28 15:40 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
> +                Int32(accountIndex.index),
I hadn't noticed that there were also calls to `zcashlc_*` in this file. Please make the `LCZip32Index` typealias accessible here and use it in place of `Int32`.

2024-11-28 15:40 UTC, daira commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
> +                    Int32(accountIndex.index),
Same comment as [above](https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/pull/1515/files#r1862404566).

2024-11-28 15:47 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Parameter account: the index of the account
```suggestion
    /// - Parameter accountIndex: the ZIP 32 index of the account
```

2024-11-28 15:48 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Returns: `AccountBalance`, struct that holds sapling and unshielded balances or `nil` when no account is associated with `account.index`
```suggestion
    /// - Parameter accountIndex: the ZIP 32 index of the account
    /// - Returns: `AccountBalance`, struct that holds sapling and unshielded balances or `nil` when no account is associated with the given ZIP 32 index
```

2024-11-28 15:50 UTC, daira commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    // TODO: [#1512] Only one instance of hardcoded account index has been removed in deeper levels and moved here, needs to be resolved i 1512
```suggestion
    // TODO: [#1512] Only one instance of hardcoded account index has been removed in deeper levels and moved here, needs to be resolved in #1512
```

2024-11-28 16:00 UTC, daira commented on Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
> +        synchronizer.getSaplingAddress(accountIndex: Zip32AccountIndex(3)) { accountIndex in
```suggestion
        synchronizer.getSaplingAddress(accountIndex: Zip32AccountIndex(3)) { result in
```

2024-11-28 16:02 UTC, daira commented on Tests/OfflineTests/DerivationToolTests/DerivationToolMainnetTests.swift
> +        let spendingKey = try derivationTool.deriveUnifiedSpendingKey(seed: seedBytes, account: Account(0))
This change doesn't seem to have been applied.

2024-11-28 16:04 UTC, daira approved these changes
utACK with blocking comments.

2024-11-29 07:47 UTC, LukasKorba commented on Tests/OfflineTests/DerivationToolTests/DerivationToolMainnetTests.swift
> +        let spendingKey = try derivationTool.deriveUnifiedSpendingKey(seed: seedBytes, account: Account(0))
Updated, there were 3 more instances of account: Account(0) in Tests so I updated those as well.

2024-11-29 07:50 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
> +                Int32(accountIndex.index),
Updated

2024-11-29 07:50 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackend.swift
> +                    Int32(accountIndex.index),
Updated

2024-11-29 07:51 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    /// - Returns: `AccountBalance`, struct that holds sapling and unshielded balances or `nil` when no account is associated with `account.index`
Updated

2024-11-29 07:52 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +    // TODO: [#1512] Only one instance of hardcoded account index has been removed in deeper levels and moved here, needs to be resolved i 1512
Updated

2024-11-29 07:52 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    /// - Parameter account: the index of the account the proposal should be made from.
Updated

2024-11-29 07:54 UTC, LukasKorba commented on Tests/OfflineTests/ClosureSynchronizerOfflineTests.swift
> +        synchronizer.getSaplingAddress(accountIndex: Zip32AccountIndex(3)) { accountIndex in
Fixed

2024-11-29 07:58 UTC, merged

2024-12-02 01:18 UTC, daira reviewed
Post-hoc ACK 6505d5f865db2f3baddf4d32c6c1b7660405922c