Import ufvk ffi preview
Electric-Coin-Company/zcash-swift-wallet-sdk pull request #1517
Opened 2024-12-04 13:10 UTC by LukasKorba

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-12-04 18:40 UTC, nuttycom requested changes
This looks like it has a problem to me, which is that by just picking the first account in a lot of cases it may get inconsistent results. The order of accounts is nondeterministic, and it shouldn't be left to chance even if it was deterministic; the account that's in use needs to be tracked explicitly.

2024-12-04 18:40 UTC, nuttycom commented on Example/ZcashLightClientSample/ZcashLightClientSample/Get Address/GetAddressViewController.swift
> +            guard let account = try? await synchronizer.listAccounts().first else {
Is taking the first account correct here? Or should the whole view track what account it's on? The order of the accounts may be nondeterministic.

2024-12-04 18:40 UTC, nuttycom commented on Example/ZcashLightClientSample/ZcashLightClientSample/Get Balance/GetBalanceViewController.swift
> +            guard let account = try? await synchronizer.listAccounts().first else {
Same question here, we shouldn't assume any ordering of accounts.

2024-12-04 18:40 UTC, nuttycom commented on Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
> +            guard let account = try? await synchronizer.listAccounts().first else {
Same thing here.

2024-12-04 18:47 UTC, nuttycom commented on Example/ZcashLightClientSample/ZcashLightClientSample/Get Address/GetAddressViewController.swift
> +            guard let account = try? await synchronizer.listAccounts().first else {
Resolving as demo code.

2024-12-04 18:51 UTC, LukasKorba commented on Example/ZcashLightClientSample/ZcashLightClientSample/Get UTXOs/GetUTXOsViewController.swift
> +            guard let account = try? await synchronizer.listAccounts().first else {
Demo app code, we can follow up later.

2024-12-04 18:59 UTC, nuttycom requested changes
Overall looking good; the one thing that I think needs to be changed is that `keySource` should be optional.

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +//    public init(encoding: String, accountUUID: AccountUUID, network: NetworkType) throws {
```suggestion
```

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
>      ///  - parameter accountIndex: the ZIP32 account Index of the given UFVK
```suggestion
```

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +    //public let accountUUID: AccountUUID
```suggestion
```

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +    //public let accountUUID: AccountUUID
```suggestion
```

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        keySource: String
keySource can be optional

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        keySource: String
```suggestion
        keySource: String?
```

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +        keySource: String
```suggestion
        keySource: String?
```

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer.swift
> -    @available(*, deprecated, message: "Upcoming SDK 2.1 will create multiple transactions at once for some recipients.")
Note that these deletions should be listed in the CHANGELOG.

2024-12-04 18:59 UTC, nuttycom commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func listAccounts() async throws -> [AccountUUID]
This addition should be noted in the CHANGELOG

2024-12-04 18:59 UTC, nuttycom requested changes
Overall looking good; the one thing that I think needs to be changed is that `keySource` should be optional.

2024-12-05 08:48 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +//    public init(encoding: String, accountUUID: AccountUUID, network: NetworkType) throws {
Cleaned up

2024-12-05 08:48 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
>      ///  - parameter accountIndex: the ZIP32 account Index of the given UFVK
Cleaned up

2024-12-05 08:48 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +    //public let accountUUID: AccountUUID
Cleaned up

2024-12-05 08:48 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Model/WalletTypes.swift
> +    //public let accountUUID: AccountUUID
Cleaned up

2024-12-05 08:52 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Initializer.swift
> +                name: "",
Updated

2024-12-05 08:52 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        keySource: String
Updated

2024-12-05 08:52 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        keySource: String
Updated

2024-12-05 08:53 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +        keySource: String
Updated

2024-12-05 09:00 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> +    func listAccounts() async throws -> [AccountUUID]
Updated

2024-12-05 09:00 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer.swift
> -    @available(*, deprecated, message: "Upcoming SDK 2.1 will create multiple transactions at once for some recipients.")
Updated

2025-01-06 18:19 UTC, str4d commented on Package.swift
> +        .package(url: "https://github.com/Electric-Coin-Company/zcash-light-client-ffi", from: "0.12.0")
This needs to stop being reverted. `from` is _completely incorrect_ to use with Swift for `0.*` dependencies, because Swift's implementation of SemVer is broken for `0.*` versions (it treats them all as compatible because it uses `X.*` as the "breaking change" identifier, but SemVer specifies that anything can change across `0.*` versions).
```suggestion
        .package(url: "https://github.com/Electric-Coin-Company/zcash-light-client-ffi", exact: "0.12.0")
```

2025-01-06 18:21 UTC, str4d commented on Example/ZcashLightClientSample/ZcashLightClientSample.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "0.12.0"
This PR cannot be merged before https://github.com/Electric-Coin-Company/zcash-light-client-ffi/pull/180 is merged. However, I see that @nuttycom has already tagged https://github.com/Electric-Coin-Company/zcash-light-client-ffi/pull/180 as 0.12.0, so we cannot alter its contents, and thus we will need to merge it as-is and make any subsequent changes in subsequent releases.

2025-01-06 18:26 UTC, str4d commented on Tests/TestUtils/TestsData.swift
> +    static let mockedAccountUUID = AccountUUID(id: Array<UInt8>(repeating: 0, count: 16))
Is the all-zeroes UUID a valid UUID format? I suspect not, which might cause unexpected parsing errors if this is ever passed into the Rust side. If this were a valid UUID, then the only error you'd get when passing into the Rust backend is "unknown account UUID" (which would be correct as the backend did not generate it). Given that I think the intention of this is to be used to mock out the Rust backend itself rather than ever be passed to it, document this as such.

2025-01-07 01:23 UTC, str4d requested changes
Reviewed ce667eb18f714b1a53ba4cf1f4b9f82d025d790f. I did not review `ZcashLightClientSample` or most of the test changes.

2025-01-07 01:23 UTC, str4d commented on Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
> +
These are unnecessary here, because this method doesn't actually create transactions.
```suggestion
```

2025-01-07 01:23 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        let txIds = try await initializer.rustBackend.extractAndStoreTxFromPCZT(
```suggestion
        let txId = try await initializer.rustBackend.extractAndStoreTxFromPCZT(
```

2025-01-07 01:23 UTC, str4d commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        let transactions = try await transactionEncoder.createTransactionsFromTxIds([txIds])
```suggestion
        let transactions = try await transactionEncoder.createTransactionsFromTxIds([txId])
```

2025-01-07 01:23 UTC, str4d commented on Sources/ZcashLightClientKit/Constants/ZcashSDK.swift
> +}
I believe this is now unused. If that is the case:
```suggestion
```

2025-01-07 01:23 UTC, str4d commented on CHANGELOG.md
> +- `SDKSynchronizer.shieldFunds`, deperacted in 2.1
```suggestion
- `SDKSynchronizer.sendToAddress`, deprecated in 2.1
- `SDKSynchronizer.shieldFunds`, deprecated in 2.1
```

2025-01-07 08:58 UTC, LukasKorba commented on Package.swift
> +        .package(url: "https://github.com/Electric-Coin-Company/zcash-light-client-ffi", from: "0.12.0")
Exact it is, updated.

2025-01-07 09:09 UTC, LukasKorba commented on Tests/OfflineTests/ZcashRustBackendTests.swift
> -        XCTAssertEqual(usk.account, 0)
There is removal of `usk.account` (account property) in the first place. It's also a follow up to be resolved in #1518

2025-01-07 09:12 UTC, LukasKorba commented on Tests/PerformanceTests/SynchronizerTests.swift
> +    func _testHundredBlocksSync() async throws {
The goal was to make the suite buildable and green for the CI by marking all broken tests and removing it from the suite. The reason why this and other tests is/are broken is very likely not related to multi-account support but for some reasons long living in the code. Updated at least the TODO to point to #1521

2025-01-07 09:13 UTC, LukasKorba commented on Tests/OfflineTests/TransactionRepositoryTests.swift
> +            accountUUID: TestsData.mockedAccountUUID,
Yes, same here: The reason why this and other tests is/are broken is very likely not related to multi-account support but for some reasons long living in the code.

2025-01-07 09:17 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    func createTransactionsFromTxIds(_ txIds: [Data]) async throws -> [ZcashTransaction.Overview]
Added

2025-01-07 09:17 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
> +    func createTransactionsFromTxIds(_ txIds: [Data]) async throws -> [ZcashTransaction.Overview] {
Updated the name.

2025-01-07 09:19 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashKeyDerivationBackendWelding.swift
> +    /// - Returns: true `UnifiedAddress`
Updated

2025-01-07 09:19 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Tool/DerivationTool.swift
> +    /// - Returns: true `UnifiedAddress`
Updated

2025-01-07 09:30 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +            hdAccountIndex: Zip32AccountIndex(hd_account_index)
Updated to check and handle both cases.

2025-01-07 09:31 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +                return nil
Yes, exactly.

2025-01-07 09:31 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +                    return nil
Yes, exactly.

2025-01-07 09:32 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +                return nil
Yes, exactly.

2025-01-07 09:33 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        let pcztPtr: UnsafeMutablePointer<FfiBoxedSlice>? = pcztWithProofs.withUnsafeBytes { pcztWithProofsBuffer in
Updated

2025-01-07 09:33 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift
> +        guard let pcztPtr else {
Updated

2025-01-07 09:36 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift
> +    func importAccount(
Added

2025-01-07 09:37 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift
> +
Removed

2025-01-07 09:38 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        let txIds = try await initializer.rustBackend.extractAndStoreTxFromPCZT(
Updated

2025-01-07 09:38 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift
> +        let transactions = try await transactionEncoder.createTransactionsFromTxIds([txIds])
Updated

2025-01-07 09:40 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Constants/ZcashSDK.swift
> +}
It's used exactly at the method mentioned in the comment itself.

``` Swift
func importAccount(
        ufvk: String,
        seedFingerprint: [UInt8]?,
        zip32AccountIndex: Zip32AccountIndex?,
        purpose: AccountPurpose,
        name: String,
        keySource: String?
    ) async throws -> AccountUUID
```

2025-01-07 09:41 UTC, LukasKorba commented on CHANGELOG.md
> +- `SDKSynchronizer.shieldFunds`, deperacted in 2.1
Updated

2025-01-07 09:43 UTC, LukasKorba commented on Tests/TestUtils/TestsData.swift
> +    static let mockedAccountUUID = AccountUUID(id: Array<UInt8>(repeating: 0, count: 16))
Commented

2025-01-08 19:48 UTC, str4d commented on Tests/OfflineTests/ZcashRustBackendTests.swift
> +                try await rustBackend.getCurrentAddress(accountUUID: TestsData.mockedAccountUUID)
I completely disagree with disabling large swathes of tests in order to get a new feature in. The entire point of tests is to ensure that the changes being made don't break anything.

2025-01-08 20:12 UTC, str4d submitted a review, later dismissed
a8b1524199a8344114fe38e4861c5dbf2328f492 addresses my non-test comments, and the PR is probably fine. However, I cannot give it an ACK, because large swathes of tests have been disabled.

If @LukasKorba confirms that the now-disabled tests were in a broken state prior to this PR (and thus disabling them has no effect on the correctness checking in this PR), then I'll let the PR be merged as-is, but _only_ if #1518 is made the number 1 priority. We cannot allow this many tests to be disabled in the long term; that is an unacceptable risk. cc @true-jared.

In any case, fixing the code comment is blocking.

2025-01-08 20:12 UTC, str4d commented on Tests/TestUtils/TestsData.swift
> +    /// `mockedAccountUUID` is used to mock the rust backend for check only purposes. It's never passed to it.
This is currently false; `mockedAccountUUID` is passed into the Rust backend repeatedly. AFAICT it only happens in tests that are currently disabled, but that still makes this "never" false.

If the intention is to never pass this into the backend (and given my previous review, it should be), and the tests do not get fixed in this PR (which I _strongly_ think they should be), then update this comment to point to the issues that will fix the code in order to make this statement true.

2025-01-09 07:59 UTC, LukasKorba commented on Tests/OfflineTests/ZcashRustBackendTests.swift
> +                try await rustBackend.getCurrentAddress(accountUUID: TestsData.mockedAccountUUID)
99% of disabled tests have been broken for a long time, this PR only took some steps to mark those at least.

2025-01-09 07:59 UTC, LukasKorba commented on Sources/ZcashLightClientKit/Transaction/TransactionEncoder.swift
> +    /// Tries to fetch the transaction for the given transction ids.
Updated

2025-01-09 08:08 UTC, LukasKorba commented on Tests/TestUtils/TestsData.swift
> +    /// `mockedAccountUUID` is used to mock the rust backend for check only purposes. It's never passed to it.
Updated the comment to reflect the purpose
```
/// `mockedAccountUUID` is used in tests only and the main purpose is to make tests buildable.
    /// [#1518][#1521] fixes of Offline and Performance tests  https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/issues/1518, https://github.com/Electric-Coin-Company/zcash-swift-wallet-sdk/issues/1521
    /// will eventually address use of this mocked account and ideally remove it completely.
```

2025-01-09 19:48 UTC, str4d commented
https://github.com/Electric-Coin-Company/zcash-light-client-ffi/pull/180 (which this PR depends on) is now merged.

2025-01-09 19:49 UTC, merged